### ISSUE TITLE
Из-за обновления свайпом сломалась полоса прокрутки

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [vortexwolf/2ch-Browser#106]
С последним обновлением невозможно активировать полосу прокрутки в начале треда, вместо этого всегда срабатывает обновление. Приходится немного прокручивать тред вниз, и уже после этого пользоваться полосой прокрутки, чтобы быстро попасть в конец. Свайп у правого края дисплея (5-10% ширины, например) не должен активировать обновление, чтобы можно было пользоваться полосой прокрутки.

Если никто из 1,5 разработчиков не в состоянии осилить такой фикс - добавьте настройку, позволяющую отключить поддержку свайпов, в качестве временного решения.

**Comment by Quireg** [comment]
@CrazyDude1994 что думаешь по этому поводу?

**Comment by CrazyDude1994** [comment]
@Quireg пытался найти что-либо вообще о быстрой прокрутке, либо о похожих проблемах - ничего не нашел. Если кто-то еще попробует поискать, будет хорошо. Либо тогда действительно добавить отключение этой опции. Так как сейчас решения данной проблемы у меня нет.

**Comment by nbmrjuhneibkr** [comment]
Ну что, какой-нибудь фикс этой проблемы есть смысл раньше 2018 года ждать?

**Comment by Quireg** [comment]
@nbmrjuhneibkr добавил возможность отключать свайп.
