### ISSUE TITLE
Пропала возможность постить без капчи

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [vortexwolf/2ch-Browser#113]
Потеряли встроенный пасскод при передаче приложения от одного разработчика к другому?

**Comment by kolokolovg** [comment]
Скорее макака его забанил.

**Comment by nbmrjuhneibkr** [comment]
Никто ничего не забанил, это точно.

**Comment by Quireg** [comment]
Всё про*бано, работаю над этим.

**Comment by Quireg** [comment]
Починил, скачай новую версию.
