### ISSUE TITLE
(Не) работает уведомление о количестве новых постов

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [vortexwolf/2ch-Browser#115]
В версии 1.5.28 и ниже при открытии ранее посещенного треда (из закладок, например) на экране выводилось сообщение с количеством новых постов. В версии 1.6.0 этого нет, при открытии тред обновляется незаметно, и единственная возможность найти новые посты - читать тред и пытаться вспомнить, каких постов не было в прошлый раз.

**Comment by nbmrjuhneibkr** [comment]
Хм, а вот только что все же сработало уведомление в одном из тредов ("нет новых сообщений"). Может быть, с уведомлениями все в порядке, а проблема в том, что данные о предыдущих посещениях тредов хранятся в кэше не так долго, как раньше?

**Comment by nbmrjuhneibkr** [comment]
После еще нескольких часов использования могу с уверенностью сказать, что уведомления действительно появляются реже, чем в старых версиях. Похоже, что треды пропадают из кэша гораздо быстрее. Это серьезная проблема.

**Comment by nbmrjuhneibkr** [comment]
Или еще одно возможное объяснение: уведомления появляются только при открытии тредов, уже посещенных в течение текущего сеанса работы приложения. А для всех тредов, которые открывались раньше - не работают. В любом случае, это надо фиксить.

**Comment by kolokolovg** [comment]
Переписывайте сетевую часть как я хотел но не стал. 
В нормальном режиме одновременно не больше 5 тредов стоит отслеживать.  
Воркер пул асинхронный,  чекает дельта джейсон треда и сохряняет в бдшку. 
Если тред ее открывался долго воркер мрет по ттл. Уведомление отдельным воркером. Чекаем бд на новые записи

**Comment by kolokolovg** [comment]
А насчет новых постов хешмапа хватит. Номер треда последний прочитаный пост

**Comment by Quireg** [comment]
Проверил по коду - всё так и должно быть. Автообновление треда не работает если зайти с вкладки History\Favorites\Opened tabs. Работает для ранее просмотренных тредов если заходить через общий список тредов. Проверьте если у вас тоже так. Предлагаю оставить как есть.
