### ISSUE TITLE
Ограничение размера кэша

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [vortexwolf/2ch-Browser#116]
Надо что-то с этим делать. 25МБ - это очень мало. Либо увеличить, либо сделать настраиваемым. Неограниченный кэш - плохая альтернатива. И еще была бы очень полезна возможность не сохранять в кэше GIF-файлы (а также webm при включенном внутреннем плеере) - из-за них все так быстро переполняется.

**Comment by Quireg** [comment]
Кэш теперь настраиваемый(30-300 Мб). На счёт второго - давай оставим всё как есть. Если с новыми размерами кэша проблема будет актуальной - что-то будем думать.
