### ISSUE TITLE
Быстро сменить адрес сервера

### ISSUE THREAD

**Issue by ololoe** [vortexwolf/2ch-Browser#119]
Как минимально модифицировать прогу, чтобы она отправляла посты на свой сервер? Нужна возможность быстро включать и отключать эту фишку.

**Comment by vortexwolf** [comment]
Можно отредактировать MakabaUrlBuilder.java, поменять ссылку в getPostingUrlApi на свой сервер, после чего пересобрать апк.

**Comment by Quireg** [comment]
Тебе нужен доступ к 2ch.hk с Украины? Я вскоре добавлю поддержку прокси в апликуху.

**Comment by ololoe** [comment]
Нет, мне нужно чтобы посты шли на мой локальный сервер, который будет делать полезные вещи. А в случае если я не дома чтобы это можно было быстро отключить.

**Comment by Quireg** [comment]
Тогда совет вортекса тебе подходит. В интерфейсе это не нужно имхо. Только возможно будет ругаться на SSL.

**Comment by ololoe** [comment]
А как добавить элемент гуя которым это можно будет переключать? Ну или в настройки на худой конец.
Как там будет с подписью программы?

**Comment by Quireg** [comment]
Читай разработку под андроид, не задавай глупых вопросов. Ты можешь подписать сам и оно отлично будет работать.

**Comment by ololoe** [comment]
Боюсь, это будет мой первый и последний проект для андроида :)
