### ISSUE TITLE
Не загружаются доски, проблема с защищённым соединением

### ISSUE THREAD

**Issue by anmiles** [vortexwolf/2ch-Browser#125]
Список досок грузится, при входе на любую пишет: 
==========
Это соединение является недоверенным. Безопасность защищённого соединения не гарантирована: сертификат не может быть проверен.
Возможные решения:
- Попробуйте установить в настройках домен по умолчанию "2ch.hk"
- Если вы понимаете, что происходит, вы можете установить в настройках: "Игнорировать ошибки SSL".
==========

В настройках домен выставил 2ch.hk - ошибка та же.
Поставил галку игнора ошибок SSL - ошибка "Невозможно использовать JSON API. Откройте страницу во внешнем браузере".
Снял галку "Использовать HTTPS" - ошибка "Невозможно открыть страницу"

**Comment by Quireg** [comment]
Попробуй с другого провайдера, может кто-то балуется с сертификатами.

**Comment by anmiles** [comment]
Попробовал с других провайдеров (в том числе через вайфай домашнего провайдера) - результат тот же.
Пробовал совет "Откройте страницу во внешнем браузере" - со всех тех провайдеров в мобильном хроме 2ch.hk открывается, без проблем с сертификатами.

**Comment by Quireg** [comment]
Всё еще плохо?

**Comment by anmiles** [comment]
Проблема видимо оказалась в телефоне.
Купил новый, вот попробовал - всё работает :)
Старый был с андроидом 4.4.2, может быть у китката какие-то свои заморочки

**Comment by Quireg** [comment]
Hurray!
