### ISSUE TITLE
Капча невалидна

### ISSUE THREAD

**Issue by Exeteres** [vortexwolf/2ch-Browser#126]
Андроид 8.0
При вводе верной капчи всплывает тост "Капча невалидна". Куда копать?

**Comment by Exeteres** [comment]
Фикс в последней сборки с гитхаба. Просто сначала скачал с 4pda, там версия старая.

**Comment by kolokolovg** [comment]
Обезьяна ж сломала двачкапчу.
Только гуглокапча и пашет
