### ISSUE TITLE
Редактор ввода сообщения в тред.

### ISSUE THREAD

**Issue by Valid093** [vortexwolf/2ch-Browser#13]
Дорогой товарищ, разработчик. Сделайте пожалуйста кнопки форматирования текста (жирное, косое, сполер etc) побольше так как на 10' очень неудобно по ним попадать. Зарание спасибо.

**Comment by vortexwolf** [comment]
Сделал чуть больше, 40dip вместо 25px. Если недостаточно - напиши, какой точно размер нужен.
