### ISSUE TITLE
Ввод капчи в landscape режиме.

### ISSUE THREAD

**Issue by hermanstankov** [vortexwolf/2ch-Browser#15]
ОП, сделай, чтобы можно было вводить капчу в ландшафтном режиме, а то неудобно каждый раз переворачивать телефон или запоминать ее.
Это очень просто: в `EditText`, где нужно вводить _Confirmation Code_ добавь 

> android:imeOptions="flagNoFullscreen"

Джва года жду такого.

**Comment by vortexwolf** [comment]
В первый раз о таком слышу, но если эта строка действительно все исправит - значит добавлю.

**Comment by vortexwolf** [comment]
Добавил в версии 1.3.7
