### ISSUE TITLE
Neutron

### ISSUE THREAD

**Issue by anon228** [vortexwolf/2ch-Browser#17]
Не могли бы вы сделать в теме Neutron цвет шрифта белым, а не синим. Синий цвет плохо читаем на черном фоне.

**Comment by vortexwolf** [comment]
В обычном сайте он тоже синий, так что пока Абу не поменяет, то и здесь будет таким же.

Все же ты можешь придумать новую тему по аналогии с Theme_Neutron_Base [отсюда](https://github.com/vortexwolf/2ch-Browser/blob/development/res/values/styles.xml), и если будет достаточно отличаться от существующей, то можно добавить в релиз.
