### ISSUE TITLE
добавь "копировать адрес ссылки" у картинки

### ISSUE THREAD

**Issue by SergeyS3** [vortexwolf/2ch-Browser#18]
надоело уже открывать браузер и копировать ссылку оттуда

**Comment by vortexwolf** [comment]
Разве "Поделиться ссылкой" не делает то, что нужно? Зачем именно копировать?

**Comment by vortexwolf** [comment]
> вк
> :)

Предлагаю тебе вернуться в свой любимый паблик вдурове. А сосач под вбыдлятник подстраиваться не будет.
