### ISSUE TITLE
Пасскод

### ISSUE THREAD

**Issue by PEKALOLKA** [vortexwolf/2ch-Browser#23]
Сделай так, чтобы после каждого нажатия "ок" в поле "пасскод" он его проверял, а не только первый раз! Потому что потом на компе сессия обрывается, и если её восстановить, то на ведре уже нихуя не восстановить, даже после перезапуска приложения он не проверяет повторно пасскод.

**Comment by vortexwolf** [comment]
Исправил в версии 1.3.10
