### ISSUE TITLE
0chan browser

### ISSUE THREAD

**Issue by Perevedko** [vortexwolf/2ch-Browser#3]
Слушай, у меня появилась идея форкнуть двощ браузер под нульчан. Если запилю, разместишь на гуглоплее?

**Comment by onanim** [comment]
Ты уже запилил на нульчане апи?

**Comment by Perevedko** [comment]
Да я уж поискал до этого апи нульча и не нашёл его. Хуёво, что ж.

**Comment by vortexwolf** [comment]
Напиши парсер HTML-разметки и класс с 2 методами: возврат списка тредов, возврат списка постов. Тогда будет несложно добавить.

**Comment by magicgoose** [comment]
парсер HTML-разметки ещё никто не взялся делать? я могу попробовать, если чо

**Comment by vortexwolf** [comment]
Если кто-то сможет сделать HTML wakaba parser, то пусть начинает. Как только будет готовый вариант - тогда и добавлю.

**Comment by Perevedko** [comment]
Скоро запилю парсер нульчана.

**Comment by rozhok** [comment]
А он еще живой? Нульчан?

**Comment by magicgoose** [comment]
не думаю

**Comment by magicgoose** [comment]
но было бы круто добавить 4chan и hiddenchan (последний, правда, просто так не будет у всех работать, но кто в теме, тот разберётся)

**Comment by rozhok** [comment]
Позакрывать бы все эти тикеты которые по два года без движения висят...
