### ISSUE TITLE
Быстрофотка

### ISSUE THREAD

**Issue by KOLANICH** [vortexwolf/2ch-Browser#31]
Не хватает возможности сфоткать и сразу прикрепить.

**Comment by magicgoose** [comment]
это очевидно, как сделать — в принципе, можешь взять и написать

**Comment by vortexwolf** [comment]
Так напиши код, т.к. мне совсем не очевидно.

**Comment by magicgoose** [comment]
@vortexwolf 
неявный интент, запускающий камеру, в onActivityResult берём фотку из data и постим её, как оыбчно
как-то так

если у меня будет время что-то править тут, я скорей поправлю что-нибудь из багов, которые **лично мне** мешают :D

**Comment by Quireg** [comment]
@KOLANICH добавил такую возможность

**Comment by KOLANICH** [comment]
спасибо, но я им уже не пользуюсь.
