### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by gjkhldffgh** [vortexwolf/2ch-Browser#33]
кароче когда такая фигня 
![Uploading 2013-08-12 02.49.14.png . . .]()
типа не полный текст показывает и когда нажимаешь обновить или когда автообновление проходит - текст опять скрывается и приходится жать опять "показать полный", заебывает

**Comment by gjkhldffgh** [comment]
![2013-08-12 02 49 14](https://f.cloud.github.com/assets/5209844/944839/3204d9a4-02e1-11e3-8a9a-f8638a963921.png)

**Comment by vortexwolf** [comment]
Причина бага понятна, но пока еще не придумал, как правильно исправить. Потом буду пробовать исправить..
