### ISSUE TITLE
некоторые тесты не проходят

### ISSUE THREAD

**Issue by magicgoose** [vortexwolf/2ch-Browser#37]
некоторые тесты валятся с исключениями (ошибки вида 
android.content.res.Resources$NotFoundException) - это очень странно и я пока не понял, почему

на девайсе (gionee iq275) валятся все тесты на работу с датой - а всё потому, что не совпадают форматы дат

также не проходит `testTrimBr` - но JUnit ёбу дал и показывает странное сообщение junit.framework.ComparisonFailure: expected:<... ...> but was:<......>
несмотря на то, что ожидаемое значение `test<br/>3`

**Comment by vortexwolf** [comment]
Тесты с датами работают в зависимости от настроек телефона, их для всех не исправишь. Остальные тесты исправлены.
