### ISSUE TITLE
Загрузка картинок при прокрутке.

### ISSUE THREAD

**Issue by misuzu** [vortexwolf/2ch-Browser#38]
Прокрутка треда тормозит, если в треде есть картинки, которые не загрузились.

**Comment by vortexwolf** [comment]
Вряд ли именно из-за картинок, т.к. если отключить их в настройках, производительность не изменится. Надо поискать какие еще могут быть причины.

**Comment by rozhok** [comment]
Проблема с тормозящими списками в history/tabs не была заведена? У меня тормозит постоянно. Так же в наличии проблема как и у @misuzu , когда картинки прогружаются то список тредов бодро работает.
