### ISSUE TITLE
новый просмотрщик картинок очень плох

### ISSUE THREAD

**Issue by magicgoose** [vortexwolf/2ch-Browser#45]
есть 2 проблемы
первая — он не позволяет увидеть картинку в полном размере (можно растянуть её, но детализации это не добавит — картинка просто будет замыленной)
вторая — если по-быстрому пролистать несколько картинок подряд, приложение падает (вангую, что из-за недостатка памяти)

проверял на sony xperia z

если это всё нельзя пофиксить, сделай хотя бы, чтобы можно было в настройках выбрать старый просмотрщик...

**Comment by vortexwolf** [comment]
Детализация была уменьшена специально до 800 пикселей, иначе были бы вылеты, Баг с прокруткой потом проверю, но вряд ли воспроизведется.

**Comment by magicgoose** [comment]
но если открыть картинку ОП из списка тредов, она открывается по-старому, можно увидеть в полном размере, и ничего не вылетает.
хардкодить лимит в 800 пикселей — это как-то странно, у девайсов памяти разное количество и экраны разные. на экране с большим dpi такой лимит выглядит несколько странно
реально, может просто добавить опцию использования старого просмотрщика? с ним всё заебок было и без уменьшения.

**Comment by vortexwolf** [comment]
800 правильное значение, т.к. с ним приложение не вылетает, а если поставить 1000, то вылетает гораздо чаще.
Все же добавил в опциях чекбокс для возврата предыдущего просмотрщика.

**Comment by magicgoose** [comment]
ты уж определись, вылетает чаще, или просто вылетает
а то получается, что и с 800 вылетает (в принципе, так и есть)

вообще это решается использованием очищаемого кэша (очищать можно например [отсюда](https://developer.android.com/reference/android/app/Application.html#onTrimMemory%28int%29))

за чекбокс огромное спасибо

**Comment by vortexwolf** [comment]
Если даже с 800 вылетает - тогда надо менять телефон на менее глючный и менее китайский. И тем более будут проблемы в каком-нибудь gif-треде, где каждая картинка по 4Мб.
На данный момент в последней версии 1.4.2 поменял просмотрщик на галерею из браузеров. Теперь проблема 1 исправлена, а проблема 2 останется у кого-то надолго, т.к. у меня не воспроизводится.

**Comment by magicgoose** [comment]
судя по наличию в коде класса `FixedSubsamplingScaleImageView` и его описанию, проблемы уже не должно быть?
если так и есть, то пора этот issue выпилить 8)

**Comment by vortexwolf** [comment]
Да, я думаю, в текущем просмотрщике гораздо меньше проблем и вылетов, чем в PhotoView, который был когда-то.
