### ISSUE TITLE
Борды

### ISSUE THREAD

**Issue by KOLANICH** [vortexwolf/2ch-Browser#47]
Грузите список борд с 2ча, а не используйте заshitый

**Comment by vortexwolf** [comment]
Из-за наличия нецензурных борд я специально оставил предопределенный урезанный список.

**Comment by KOLANICH** [comment]
Тогда обновите его, включив все "цензурные" доски. Да и вообще не вижу в этой "цензуре" смысла : через сайт все "нецензурные" доски видны.

**Comment by KOLANICH** [comment]
Или грузите список с сервера и отфильтровывайте "нецензурные".

**Comment by vortexwolf** [comment]
На сайте разрешены, в Google Play запрещены. 
К тому же совсем цензурных на сайте нет, но я оставил только те, у которых наибольшая вероятность пройти проверку в магазине. Все приложения для просмотра чанов сделали именно так.

**Comment by vortexwolf** [comment]
И официальная ссылка, показывающая что запрещены текстовые надписи и сообщения связанные со всякой эротикой:
http://play.google.com/about/developer-content-policy.html
"Apps that contain or promote pornography are prohibited; this includes sexually explicit or erotic content, icons, titles, or descriptions."

**Comment by KOLANICH** [comment]
Я знаю. Поэтому предлагаю работать не по схеме белого списка, а по схеме чёрного. Загрузить список досок, вырезать категорию 18+ и отобразить остальные. Или просто получить информацию об источнике, и если это гугл, то ограничить функциональность.
