### ISSUE TITLE
503 на всех форумах

### ISSUE THREAD

**Issue by YokiToki** [vortexwolf/2ch-Browser#52]
![screenshot_2014-08-10-00-12-33](https://cloud.githubusercontent.com/assets/1845813/3866939/e4448842-1fe8-11e4-9e19-61d679031e32.png)

Android 4.4.2, приложение установлено с маркета

**Comment by vortexwolf** [comment]
Абу удалил существующий JSON API, хотя мог бы оставить для поддержки существующих устройств. Не знаю, есть ли новый API, и насколько сложно будет исправить существующий код. Если появился новый - то напиши какой-нибудь документ, чем отличается от предыдущего API и как его исправить.

**Comment by dev0x13** [comment]
2ch-Browser / src / com / vortexwolf / chan / boards / dvach / DvachApiReader.java: 85, 86
// later test new api
// String uri = String.format("/makaba/mobile.fcgi?task=get_thread&board=%s&thread=%s&post=0", boardName, threadId);
А откуда эти строки взялись?

**Comment by dev0x13** [comment]
Со страницы Абу:

Из плохого.
Сломался куклоскрипт. Сломались мобильные приложения. Надеюсь, разработчики их допилят в ближайшее время, все инструменты для мобильных приложений работают и обновлены. JSON, мобильное API.
Напомню, JSON доступен при запросе на любой тред/список тредов, вместо .html меняем на .json

Мобильное API: https://2ch.hk/makaba/mobile.fcgi?task=get_thread&board=test&thread=51673765&num=51673765 где num = номер поста

https://2ch.hk/makaba/mobile.fcgi?task=get_thread&board=test&thread=51673765&post=2 где post = порядковый номер поста в треде

http://2ch.hk/makaba/mobile.fcgi?task=get_boards - список досок

Есть спорные моменты как с вопросом, где должны находиться ответы на пост, сверху или снизу.

Пожалуйста, пишите свои мнения, пожелания и вопросы ИТТ.
Или сюда https://2ch.hk/abu/res/31512.html

**Comment by vortexwolf** [comment]
Когда-то собирался проводить этот test, но там было много отличий.
К тому же не написано, как отправлять сообщения, придется самому тратить время и узнавать как это сделано.

**Comment by dev0x13** [comment]
Есть подозрение, что постинг пока работает через Вакабу. Или я что-то путаю?
![wakaba](https://cloud.githubusercontent.com/assets/5624568/3901690/87124e74-22af-11e4-832a-32f9bbe22bb1.png)

**Comment by vortexwolf** [comment]
если через вакабу, то может и не придется много менять.

**Comment by dev0x13** [comment]
Мы в тебя верим. Попробую в ближайшее время форкнуть и сам посмотреть, что изменилось.

**Comment by vortexwolf** [comment]
Оказывается, на макабу переведены не все доски. Некоторые еще на вакабе и открываются в приложении.
Старое API:
2ch.hk/pr/wakaba.json - треды с нулевой
2ch.hk/pr/1.json - треды с номером страницы
2ch.hk/pr/res/375489.json - любой тред

Новое API:
2ch.hk/b/index.json - треды с нулевой
2ch.hk/b/1.json - треды с номером страницы
2ch.hk/b/res/123456.json - любой тред вариант 1
2ch.hk/makaba/mobile.fcgi?task=get_thread&board=b&thread=123456&num=123456 - любой тред вариант 2
2ch.hk/makaba/mobile.fcgi?task=get_boards - все борды

**Comment by dev0x13** [comment]
А почему тогда из приложения 503 на всех досках?

**Comment by vortexwolf** [comment]
Почему у кого-то 503 - не знаю. У меня или ошибка 404 на досках с макабой, или открываются нормально если до сих пор вакаба. 
В 2ch.hk/faq написано для ошибки 503 "Откройте меньше тредов", но в данном случае здесь что-то другое..

**Comment by dev0x13** [comment]
Включил HTTPS, теперь не открываются только доски с Макабой. Можешь, пожалуйста, где-нибудь отписать, что для решения проблемы с 503 нужно включить HTTPS?
