### ISSUE TITLE
призываем в тред

### ISSUE THREAD

**Issue by rkbienhujrmbn** [vortexwolf/2ch-Browser#53]
Анон просит зайти в тред, высказаться по поводу дальнейшей разработки
https://2ch.hk/mobi/res/331787.html

**Comment by vortexwolf** [comment]
Что-то этот тред закрыт и туда нельзя отвечать.

**Comment by nbmrjuhneibkr** [comment]
Открыли тред уже.

**Comment by magicgoose** [comment]
"The page you are looking for cannot be found."
