### ISSUE TITLE
Cloudflare (без капчи)

### ISSUE THREAD

**Issue by miku-nyan** [vortexwolf/2ch-Browser#57]
В треде уже было, запощу еще сюда.
С некоторых IP проверка cloudflare на домене 2ch.hk (без капчи), ошибка при постинге.
Выдает подобную страницу с кодом 503: http://pastebin.com/uPX4rSMN при запросе html страниц и при постинге (при запросе json проверка не производится). Редирект через 5 секунд.

На домене 2ch.pm такой проблемы (пока?) нет. Так нужно это фиксить вообще? Как это реализовывать, не вручную же разбирать этот js омск? Пока только идея запускать webkit (WebView?) иммитируя нормальный браузер и сохраняя cookies.

**Comment by vortexwolf** [comment]
Можешь проверить, всегда ли значение lafCzZn.vQmKC одинаковое?  Если нет, то можно попробовать распарсить. Начало !+[] это 1, в середине или +!![] это +1, или +[] это +0. Сложности только со скобками.
Хотя если это случается при отправке сообщений, тогда не знаю, как нормально передать решение этого шифра, а потом и само сообщение.

**Comment by miku-nyan** [comment]
Не одинаковое. http://pastebin.com/26v7ppRw

**Comment by miku-nyan** [comment]
Посмотри пока реализацию с webview (последний коммит), так вроде работает. Может что улучшить, или рефакторинг сделать?

**Comment by vortexwolf** [comment]
Если этот CloudflareCheckService работает, тогда пусть будет, т.к. я у себя проверить не могу. Только надо бы фигурные скобки добавить к if-выражениям, а в остальном вроде все написано логично.
