### ISSUE TITLE
заёбывающие Toastы при автообновлении

### ISSUE THREAD

**Issue by magicgoose** [vortexwolf/2ch-Browser#58]
лучше сделать, чтобы Toast показывался только, если данная доска открыта прямо сейчас, в противном случае можно фигачить уведомления в Notification, + можно использовать Inbox style и группировать всё в 1 уведомление. Или, как вариант, не показывать никаких уведомлений, а просто создать отдельную активити, где будет список тредов, где появились новые сообщения.

я могу это сделать сам, если согласишься с этой мыслью и потом примешь пулл реквест.

**Comment by magicgoose** [comment]
https://github.com/magicgoose/2ch-Browser/compare/additions?expand=1

**Comment by vortexwolf** [comment]
Что-то ты совсем не то написал, надо было в отдельный класс вынести, а не в MainApplication все забрасывать. Потом посмотрю сам, как можно лучше сделать.

**Comment by magicgoose** [comment]
ну, это черновая версия, закинуть всегда можно куда-нибудь отдельно

**Comment by Quireg** [comment]
@magicgoose эта проблема еще актуальна? Если да, опиши более детально.

**Comment by magicgoose** [comment]
ты б ещё через 5 лет спросил. уже давно вообще не имею дела с данной имиджбордой.
