### ISSUE TITLE
Eclipse vs Android Studio / IntelliJ IDEA

### ISSUE THREAD

**Issue by magicgoose** [vortexwolf/2ch-Browser#60]
я предлагаю окончательно и бесповоротно попячить Eclipse, например, и хранить либо файлы проектов IDEA, либо что-нибудь кроссIDEшное (Gradle)
потому что (фришная) IDEA уже давно даёт Eclipse просраться, там лучше сделано практически **всё,** в том числе XML-редактор для UI и прочих ресурсов. (поддержка андроида из коробки, безо всяких плагинов и "Android Studio") Единственное, с чем у меня не было толком опыта — это **нативные** либы (в андроидных проектах), может быть, там есть какие-то подводные камни… в любом случае, я считаю, что оно стоит того, чтобы хотя бы попробовать

**Comment by miku-nyan** [comment]
Поддержка андроида из коробки не в чистой IDEA, а в Android Studio. С таким же успехом можно скачать и сайта гугла "ADT Bundle", который суть Eclipse с уже установленным плагином.
А вообще хз, пусть vortexwolf решает.
Лично я считаю, что не нужно, во всяком случае пока. Во-первых, она ещё бета (и гугл официально предлагает использовать eclipse). Во-вторых, субъективно, свинговый интерфейс выглядит как говно, на ШГ просто невозможно смотреть (по крайней мере, в линуксе).
Не может в ndk - другой вопрос (это пока не такая большая проблема, у нас нативная библиотека только для воспроизведения гифок, сторонняя).

**Comment by magicgoose** [comment]
> Поддержка андроида из коробки не в чистой IDEA

таки уже и в чистой, я гарантирую это.

> Во-вторых, субъективно, свинговый интерфейс выглядит как говно, на ШГ просто невозможно смотреть (по крайней мере, в линуксе).

ну, к этому привыкнуть легко со временем, зато то же автодополнение в идее в разы лучше.
кстати, в OS X норм выглядит всё.

и да, дропать _поддержку_ Eclipse никто не заставляет, я специально упомянул **Gradle** (вообще, это был бы самый цивилизованный вариант, т.к. можно и скриптом собирать + управление зависимостями и прочие ништяки, но его сложнее осилить)

**Comment by miku-nyan** [comment]
К вот этому привыкнуть?
![151](https://cloud.githubusercontent.com/assets/8571961/4419690/6f4851c6-456e-11e4-9a31-1152ed0912aa.png)

**Comment by miku-nyan** [comment]
> дропать поддержку Eclipse никто не заставляет
> я предлагаю окончательно и бесповоротно попячить Eclipse

Насчёт gradle можно подумать.
А скриптом и так можно собирать, см. ant. Я так, собственно, свои сборки (которые x2ch) и собираю.

**Comment by magicgoose** [comment]
> я предлагаю окончательно и бесповоротно попячить Eclipse

в смысле eclipse-specific файлы в репозитории

> К вот этому привыкнуть?

можно менять шрифты в настройках идеи, и ещё, говорят, можно [чинить антиалиасинг](http://stackoverflow.com/a/19697698/1418097)

**Comment by magicgoose** [comment]
> Во-первых, она ещё бета

в About не смог найти слово beta
ЧЯДНТ?
[screen shot 2014-09-26 at 3 28 28 pm](https://cloud.githubusercontent.com/assets/1442206/4419784/48c271ba-4570-11e4-9315-0965705e5702.png)

**Comment by miku-nyan** [comment]
![152](https://cloud.githubusercontent.com/assets/8571961/4419835/d49109ae-4570-11e4-8ebf-675f881633e0.png)
В чистой IDEA, (если там есть поддержка андроида), скорее всего, тот же самый плагин.
Гугл [предлагает](https://developer.android.com/sdk/index.html) в первую очередь ADT Bundle, предупреждает, что Android Studio пока Beta

**Comment by magicgoose** [comment]
Там есть поддержка андроида. Опять же, никаких бет.
[screen shot 2014-09-26 at 3 51 34 pm](https://cloud.githubusercontent.com/assets/1442206/4420002/9839f77e-4573-11e4-8d86-af35576850b9.png)
А гугловцы могли тупо забить болт на Android Studio, но это не показатель.

**Comment by vortexwolf** [comment]
Идея не нужна, Eclipse лучше и официально продвигается гуглом в их ADT Bundle. Даже сотрудники гугла пользуются Eclipse.
Gradle я не осилил, мне гораздо проще выбрать правой кнопкой мыши в контекстном меню "Export signed application" и через пару диалогов получить готовый apk.

**Comment by magicgoose** [comment]
> Eclipse лучше и официально продвигается гуглом в их ADT Bundle. Даже сотрудники гугла пользуются Eclipse.

Они лахи просто…
А ты пробовал хоть идею, или просто уверен, что ничего лучше Eclipse не может быть? Просто я раньше тоже так думал, пока не попробовал, хотя она тогда ещё даже не та была, что сегодня, было больше багов и подвисаний.

Gradle не такая сложная херь, в принципе могу помочь, чуток имел дело с ним, обращайся
нужно 1 раз создать скрипты-описания проектов, и тоже всё в 1 действие будет, причём строго детерминированно, а не как в Eclipse, когда одни и те же действия работают через раз

**Comment by vortexwolf** [comment]
Мне не так важно что там лучше для других языков, но именно для Андроида нет ничего лучше Eclipse. 
С ним все просто: выбираешь в диалоге Import existing project, потом в контекстном меню Export APK и файл собирается из коробки, без написания каких-то дополнительных скриптов и установки плагинов. Вот именно эти важные вещи андроид студия не умеет, зато у них есть какие-то мифические рефакторинги и автокомплиты, без которых я вполне обхожусь. А еще в андроид студии очень бесполезный LogCat, у меня так и не получилось нормально увидеть логи с сообщениями и ошибками.
В итоге, может эта андроид студия и лучше для обычной джавы, но точно не подходит для андроид-инфраструктуры.

**Comment by magicgoose** [comment]
> С ним все просто: выбираешь в диалоге Import existing project, потом в контекстном меню Export APK и файл собирается из коробки, без написания каких-то дополнительных скриптов и установки плагинов.

IDEA умеет это (импортировать проект, и APK делать), если не веришь, могу скринкаст записать. причём, там это делается едва ли не проще…

> А еще в андроид студии очень бесполезный LogCat, у меня так и не получилось нормально увидеть логи с сообщениями и ошибками.

ну это вообще пушка
там есть это, и фильтры все те же самые есть, разница лишь в том, что тормозят меньше и нет спонтанных косяков с невозможностью скопировать текст, как это было в Eclipse.
что значит _"нормально увидеть"?_

**Comment by vortexwolf** [comment]
Аналогичная функциональность там конечно есть, но в худшем исполнении. 
В эклипсе для меня нет никаких проблем, ни разу не видел мифических вылетов или невозможности копирования или что еще придумывают, в то время как в недоработанных бетах или сторонних неофициальных плагинах проблем точно будет гораздо больше. 

Вот может когда-нибудь гугл закончит свою студию, сделает официальной и рекомендованной, напишет гайд по переходу, тогда можно будет и переходить. Но этого в ближайшее время не произойдет, разрабатывают с 2013 и до сих пор бета, фейл.

**Comment by magicgoose** [comment]
> в то время как в недоработанных бетах

IDEA — вполне себе финальная, как и андроидный плагин, см. скриншоты выше.

> Вот может когда-нибудь гугл закончит свою студию, сделает официальной и рекомендованной, напишет гайд по переходу, тогда можно будет и переходить.

А зачем, если в "голой" IDEA всё есть уже? И безо всяких гайдов всё ясно и понятно.  
А на рекомендации гугла всем пофиг, они и сами их нарушают запросто… например, если вспомнить про эпичный спор на тему [нужности](http://stackoverflow.com/a/20445592/1418097)/[ненужности](http://stackoverflow.com/a/9287015/1418097) форсированного overflow menu. 
Не стоит думать о гугле, как о каком-то Б-ге, знающем ответы на все вопросы. :D

**Comment by vortexwolf** [comment]
Может и попробую потом, но если не осилю импорт проекта, значит не судьба. Тогда уж точно придется ждать официального релиза от гугла с инструкцией по переводу эклипс-проектов.

**Comment by miku-nyan** [comment]
С чего вообще весь бугурт? IDE всего лишь инструмент, не более. Каждый использует то, что ему больше нравится, наконец, привычнее. Кому-то может вообще удобнее работать в vim, кому-то в notepad.exe. В результате те же самые исходники.
Зачем ты так форсишь IDEA здесь? Исходники (т.е. java классы, файлы ресурсов) одни, да пиши у себя хоть в Microsoft Visual Studio.
Вся проблема в том, что по умолчанию в проекте IDEA папки не так расположены? Ну сделай симлинки.
Или ты хочешь предложить внедрить 100500 библиотек с зависимостями, которые сможет разрулить только gradle? Или ещё что?

**Comment by magicgoose** [comment]
Ну, я и так могу идею использовать, благо импорт проектов eclipse там работает без проблем, просто мне кажется странным, что кто-то до сих пор мучается с eclipse, когда этого уже можно не делать

**Comment by vortexwolf** [comment]
Если папки по-другому расположены, тогда менять IDE нельзя.
А с эклипсом никто не мучается, код пишется, файлы открываются, никаких проблем совсем нет.

**Comment by magicgoose** [comment]
> Если папки по-другому расположены, тогда менять IDE нельзя.

IDEA пофиг на расположение, можно как угодно располагать. Можно даже иметь несколько корневых папок с кодом, и т.д. (вот она, гибкость, и зависть пользователей Eclipse)
Поэтому переход был бы крайне лёгким, сами файлы с кодом и ресурсами трогать _вообще не нужно_ для этого.

**Comment by MarmaladeSky** [comment]
Задам вопрос тут.
У вас есть инструкция по сборке, коль вы не используете Gradle/Maven?
И если нет, то как без лишней потери времени собрать проект или импортировать в любую IDE?

**Comment by miku-nyan** [comment]
```
android update project -p . && ant debug
```

**Comment by MarmaladeSky** [comment]
Благодарствую, совсем забыл про update (разве что еще --target TARGETNAME). Проект, кстати, без каких либо проблем импортируется в IDEA.

**Comment by miku-nyan** [comment]
target указан в project.properties: android-20.
Возможно, в SDK не скачан пакет для этой версии API

**Comment by kalyaganov** [comment]
В Android Studio можно удобно редактировать ресурсы, все скомпановано. А по поводу Gradle, то там 1 раз настроил и забыл. Для сборки проекта просто нажать build. Версионность кода и приложения устанавливать тоже через скрипт сборки - меньше хлама в манифесте будет. 
![2014-09-16 16 01 10](https://cloud.githubusercontent.com/assets/5221024/4470822/3fafaf2c-492e-11e4-996b-d8cb8feca704.png)

**Comment by vortexwolf** [comment]
Ресурсы это просто xml-файлы, в блокноте тоже удобно редактировать. А Eclipse настраивается 0 раз и работает сразу.
Пора закрывать этот вопрос, хватит с меня рекламы бета-версий.

**Comment by magicgoose** [comment]
> бета-версий

ну чего ты заладил про беты, идея уже давно не бета

> Ресурсы это просто xml-файлы, в блокноте тоже удобно редактировать

так же удобно, как и в Eclipse, ты хотел сказать? что ж, недалеко от правды. (trollface.png)

**Comment by kalyaganov** [comment]
Я сделал порт на студию. Там все работает, кроме Google analytics и тестов. Но тесты и раньше вроде не работали. Если появится желание, то можете переехать в студию.

Отправил реквест.

**Comment by magicgoose** [comment]
тесты частично не работали раньше, я создавал issue, всем пофиг было.

**Comment by miku-nyan** [comment]
> все работает, кроме Google analytics и тестов
> Files changed 500

Лол.

**Comment by vortexwolf** [comment]
Да, я тоже офигел от 500 файлов. Особенно если представить, что на работе на такой change list пришлось бы кому-то делать review.

> тесты частично не работали раньше, я создавал issue, всем пофиг было.

Надо бы переделать, но тестировать особо нечего, т.к. все эти activity, adapter, asynctask нормально не потестируешь.

**Comment by magicgoose** [comment]
там какая-то более мелкокалиберная пенисня тестировалась, емнип
а вообще в приложении такого толка действительно мало чего есть смысл тестировать, если ты не маньяк тдд

**Comment by kalyaganov** [comment]
Попытка номер 2.

**Comment by rozhok** [comment]
Сделали поддержку грейдла же, нет?

**Comment by magicgoose** [comment]
Android Studio рулит, как бы, уже. Я начинал 1 проект, там всё просто заебись работает! И благодаря использованию gradle, можно легко добавить плагин retrolambda и писать на подмножестве Java 8 (то есть, Java 7 + лямбды + ссылки на методы. и наверное минус try with resources — это не проверял пока)
https://github.com/evant/gradle-retrolambda
это бомба! 

то есть, скажем, можно написать что-то типа

```
…
yobaButton.setOnClickListener(this::handleYobaClick);
…
void handleYobaClick(View sender) {
    …
}
```

или

```
yobaButton.setOnClickListener(v -> doSomething());
```

ну и всё, что связано с андроидом, в андроид студии тоже сделано уже очень круто.

**Comment by kalyaganov** [comment]
Он лямбы после компиляции убирает? В каком-нибудь большом проекте использовалось уже? Есть подводные камни? Если будет генерировать отчет об ошибках, то правильно номер строки в отчете определяется?

**Comment by magicgoose** [comment]
После компиляции остаются только class-файлы совместимые с Java 6. Большие проекты именно на Java не делал пока. Насчёт отчётов об ошибках не знаю, я не делаю ошибок™.

**Comment by vortexwolf** [comment]
Установил на рабочий макбук Андроид студию, попробую продолжить разработку на ней. Но структуру проекта менять не буду, все останется через gradle файлы.

**Comment by magicgoose** [comment]
> все останется через gradle файлы

так это и есть цель, как бэ?

**Comment by magicgoose** [comment]
@Kalyaganov retrolambda уже использую в большом проекте (точнее, даже двух), всё норм.

**Comment by Quireg** [comment]
Работаем с градлом.
