### ISSUE TITLE
Android < 4.0

### ISSUE THREAD

**Issue by magicgoose** [vortexwolf/2ch-Browser#61]
Что говорит аналитика на тему количества пользователей с андроидом < 4.0?
Может быть, можно забить болт на поддержку более старых версий? Это позволило бы облегчить приложение и ещё некоторые профиты

**Comment by magicgoose** [comment]
эээ, ну на вопрос-то можно было и ответить…

**Comment by miku-nyan** [comment]
![154](https://cloud.githubusercontent.com/assets/8571961/4419967/215ac96c-4573-11e4-92b6-f7c0c9cfdb89.png)
![155](https://cloud.githubusercontent.com/assets/8571961/4419969/24004f98-4573-11e4-815f-330e212a8d11.png)
Ну и расскажи, какие конкретно профиты ты получишь?

**Comment by magicgoose** [comment]
печалька, почти 10%
тогда об этом рано говорить, наверное
