### ISSUE TITLE
звук в webm'ках

### ISSUE THREAD

**Issue by TrallNumberFour** [vortexwolf/2ch-Browser#68]
Автор, приложение ништяк одно только но - почему в вебмках нельзя звук вырубить? запилить бы в настройках пункт отрубающийвесь звук тогда будет совсем офигенно

**Comment by Quireg** [comment]
Запилено, https://github.com/vortexwolf/2ch-Browser/commit/6854c15ffe3cff04d1a99e269d8b02da0a057c65
