### ISSUE TITLE
Не отображаются оппики тредов

### ISSUE THREAD

**Issue by astra1** [vortexwolf/2ch-Browser#70]
![tmp_26070-screenshot_2015-04-21-14-38-57-1755554191](https://cloud.githubusercontent.com/assets/4422785/7251523/d6f479c6-e834-11e4-89bb-2f3035911ff5.png)
Специально только что скачал и установил версию с дропбокса. CM11. Nexus 4

**Comment by v0vc** [comment]
Подтверждаю, CM11. Moto Defy+

**Comment by vortexwolf** [comment]
Не знаю, в чем причина. Не получается воспроизвести на эмуляторе.

**Comment by v0vc** [comment]
Прошло само собой, мб абу шатал

**Comment by 8of** [comment]
Подтверждаю. Абу шатал. Тоже был такой период с месяц назад.

**Comment by Quireg** [comment]
Expired
