### ISSUE TITLE
предложение по улучшению механизма капчи

### ISSUE THREAD

**Issue by KOLANICH** [vortexwolf/2ch-Browser#73]
Яндекс-капча лучше мутных неверно размеченных картинок гугла. Предлагаю изменить логику.
1 не юзать вебвью для гуглокапчи. Вебвью уязвим, что позволяет гуглу доставлять на телефон эксплоит. Если что - это просто параноя.
2 вместо скриптов гугла приложение должно само проверять статус капчи, если надо, отсылая гуглу фейковые данные. У меня есть подозрение, что они фингерпринтинг делают, но я это не копал.
3 если капча требуется, показывать яндекс-капчу
4 сделать поведение настраиваемым

**Comment by vortexwolf** [comment]
Абу отключал Яндекс-капчу и включал гугловую из-за превышение квоты, которую выделил Яндекс. Поэтому если Яндекс-капча не работает, то это из-за технических причин и ее не получится включить.

С гугл-рекапчей и чекбоксом в вебью надо разобраться, как оно все работает. Как альтернатива, можно всегда показывать картинку вместо чекбокса. Основная проблема, что рекапча по умолчанию очень сильно искажена и нечитаема. Это в веб-браузере она показывает легкие числа, а в приложении всегда длинные и корявые слова.

**Comment by nbmrjuhneibkr** [comment]
Как запасной вариант для параноиков можно оставить возможность выбора в настройках именно этой трудночитаемой картинки.
