### ISSUE TITLE
Зачем сломал возможность открывать превью webm в галерее?

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [vortexwolf/2ch-Browser#74]
Просили

> Добавить возможность использовать внешний видеоплеер с отключенной галереей (сейчас эта галка в настройках становится неактивной). Просто сразу открывать видео во внешнем плеере, без показа превью.

Это в новой версии сделано, но заодно выпилена возможность открывать превью webm с **включенной** галереей и внешним плеером. Почему обязательно надо каждый раз что-нибудь ломать? Исправляй.

**Comment by vortexwolf** [comment]
Основная необходимость была такой, чтобы видео открывалось не 2 нажатиями, а 1. Сейчас так и работает, при выбранной настройке внешнего видео-плеера видео открывается с одного нажатия.
Ты же предлагаешь какую-то избирательность настроек, чтобы при каком-то случае нужно было кликать 2 раза, при каком-то другом случае кликать 1 раз. И чтобы регулировалось какой-то неочевидной комбинацией настроек. Это ерунда полная.
Текущие настройки можно улучшить и дополнить, но они должны быть проще и всегда работать одинаково.

**Comment by nbmrjuhneibkr** [comment]
Это я составляю списки реквестов в треде (да и сами треды создаю). Никакой "необходимости" не было, все и так работало нормально.

Один-единственный анон попросил сделать открытие webm одним нажатием при **выключенной** галерее, потому что именно с выключенной галереей он и использовал приложение.

Это в новой версии сделано, но при этом изменено поведение программы при **включённой** галерее, о чем никто никогда не просил. Повторяю: никто и никогда.

При включённой галерее нажатие на любое превью (в т.ч. превью видео) в треде должно отправлять именно в галерею, а не сразу в какой-либо видеоплеер. Так было раньше, это всех устраивало, и это просто логично.

Если так сложно сделать разное поведение программы при открытии webm с включенной или выключенной галереей, то просто сделай настройку, позволяющую выбрать, открывать ли webm одним или двумя нажатиями. А пользователи сами разберутся, какой вариант им больше подходит.

В любом случае, выпиливать одно, чтобы сделать другое - нехорошо. Всегда должен быть выбор.

**Comment by vortexwolf** [comment]
В треде аноны сами не знали чего хотели. А для меня логично, что внешний видеоплеер должен всегда открывать видео с одного клика, без исключений. А раньше открывал с двух кликов, и тоже во всех случаях. Просто и понятно. А вот ты расписал несколько параграфов, чтобы объяснить как должно быть. Явно же видно, что это поведение слишком сложное, раз на объяснение понадобилось столько текста.
Над настройками подумаю, как их оформить, чтобы настроек было немного и было понятно что они будут делать.

**Comment by nbmrjuhneibkr** [comment]
Я расписываю несколько параграфов, чтобы максимально точно донести свою точку зрения.

Представим тред, в котором есть только webm, а картинок нет совсем. В таком треде теперь использовать галерею просто невозможно, потому что всегда будет сразу открываться внешний плеер. Для просмотра всех webm в таком треде пользователь будет вынужден проскроллить его от начала до конца, хотя в предыдущей версии мог просто использовать галерею. Это не "просто и понятно", это снижение функциональности.

Все работало нормально, никто не жаловался. Потом один анон попросил кое-что изменить. Ты изменил, но не так, как он просил. В результате нарушена работа другой функции (галереи), которой тот анон вообще не пользовался, но зато пользуюсь я и, вероятно, многие другие.

Теперь я прошу снова сделать работу галереи такой, какой она была раньше (не затрагивая быстрое открытие webm с выключенной галереей), или добавить настройки, которые позволят пользователям самим выбирать, как им удобнее. Но разработчик почему-то не хочет это делать. Я не понимаю.

**Comment by vortexwolf** [comment]
> Представим тред, в котором есть только webm, а картинок нет совсем. В таком треде теперь использовать галерею просто невозможно

В таких случаях галерея и не нужна, т.к. дублирует thumbnails из треда. Никакой функциональности такая галерея не добавляет, ведь так же легко прокрутить к следующим webm внутри треда. И в webm-тредах в каждом следующем посту новые видео, долго скроллить не нужно.

Можно добавить общую галерею в виде решетки (grid view) как отдельную страницу, где все thumbnails из треда будут в одном месте. Так галерея и сделана в некоторые чан-браузерах. Но и на такой странице я бы открывал видео по одному клику.

**Comment by nbmrjuhneibkr** [comment]
В треде может быть 500 постов, пара картинок и 20 webm. Ничего хорошего в скроллинге такого треда ради просмотра нескольких видео нет.

Ещё раз повторю: до обновления всех все устраивало, никто никогда не просил менять процесс открытия webm с включённой галереей. Но ты зачем-то это поменял и приводишь аргументы типа "мне нинужно = всем нинужно". При этом я описываю реальные сценарии использования, в которых новая версия стала менее удобна, чем предыдущая.

Вместо того, чтобы прикручивать ещё какой-то велосипед в виде ещё одной галереи, лучше сначала сделать настройки, которые позволят комфортно использовать то, что уже есть.

Блджад, я всего лишь прошу настройку, позволяющую включить открытие webm "двумя нажатиями", как это было раньше. Неужели так сложно это сделать?

**Comment by vortexwolf** [comment]
В тредах в 500 постов эти редкие видео файлы между собой не связаны, и порядок их просмотра не важен. Запутывать и усложнять настройки я просто не хочу. Я и так думаю их упростить и убрать ненужные, тем более такие настройки ни о чем "каким способом открывать webm внешним проигрывателем".
Алсо раньше, когда были только youtube видео, они открывались сразу, это было логично и никто не жаловался. И веб-версия также открывает видео сразу. Именно поэтому так, как сделано сейчас, просто и логично.

**Comment by nbmrjuhneibkr** [comment]
Я не понимаю, почему разработчик может с таким упорством отказываться идти навстречу пожеланиям пользователей.

Давай обойдётся без обсуждения отличий между YouTube-видео, которое является ссылкой в тексте поста, и прикрепленным webm-файлом, который равноценен прикреплённой картинке.

**Пожалуйста,** просто сделай возможность включить открытие webm так, как это было в предыдущей версии. В этом не может быть ничего сложного, и от этого никому не станет хуже.
Тебя никто не просил это убирать, но зато сразу же попросили это вернуть, а ты по непонятной причине отказываешься.
И любые другие настройки не надо убирать. Это не принесёт **никакой** пользы, но зато сразу сделает приложение менее функциональным. Я не вижу **ни одной** объективной причины для того, чтобы не давать пользователю настроить приложение так, как ему удобно.

Я уже говорил это автору Dashchan, скажу и здесь: когда разработчик делает приложение только под свои личные нужды, такому приложению не место в публичном доступе.

**Comment by vortexwolf** [comment]
Данный issue в гитхабе это не пожелания во множественном числе, а придирка к мелочам. А вот как желают многие пользователи - это я узнаю тестируя другие приложения и изучая что делают крупные компании-разработчики.
Урезание настроек это общепринятая практика, так делают многие. В лучшем случае самым продвинутым пользователям выдают текстовые config-файлы, но большинству не нужно разбираться в конфигурациях, они пользуются как есть и в настройки не лезут. Это не "только под личные нужды", а под "нужды большинства".
С видео сделаю так: заменю чекбокс с внешним видеоплеером на комбобокс, где можно будет выбрать варианты 1. auto; 2. WebView; 3. VideoView; 4. External + Gallery; 5. External. Все прошлые версии получат опцию auto и будут работать как и раньше, а также в зависимости от версии ОС. А кому нужно - смогут поменять.
