### ISSUE TITLE
Цифровая клавиатура для ввода капчи

### ISSUE THREAD

**Issue by libastral** [vortexwolf/2ch-Browser#80]
Сабж. Как раньше было во времена яндекс капчи.

**Comment by ololoe** [comment]
Двачую.

**Comment by vortexwolf** [comment]
Сделано в версии на дропбоксе: https://dl.dropbox.com/u/8047386/2ch-browser.apk

**Comment by ololoe** [comment]
>на дропбоксе

Но зачем?
