### ISSUE TITLE
Жопа

### ISSUE THREAD

**Issue by ololoe** [vortexwolf/2ch-Browser#83]
Везде "open in external browser"

**Comment by vortexwolf** [comment]
Это из-за cloudflare капчи, которая поменялась и ее невозможно добавить. Но возможно, что при правильном вводе в обычном браузере IP-адрес добавят в белый список и капча исчезнет.

**Comment by ololoe** [comment]
Вот это можно было бы добавить в программу.

**Comment by ololoe** [comment]
Нихрена не работает. Программу теперь можно выкидывать? Что макака говорит?

**Comment by vortexwolf** [comment]
Абу ничего не скажет, т.к. этот cloudflare это сторонний сайт. Может и можно как-то исправить, но это слишком сложно, и приходится обходить ограничение, которого не должно существовать.
Поэтому если вдруг другие приложения могут проходить эту защиту, то лучше их и использовать.

**Comment by ololoe** [comment]
Так эта макака сраная ее и включила. Сколько раз просили выключить хотя бы для скачивания файлов, давали ссылки на модули обхода флеры- только тогда он что-то делал. Я так понимаю, апи давалось по принципу двачей "вам здесь никто ничего не должен, жрите что дают"?
