### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by MarmaladeSky** [vortexwolf/2ch-Browser#85]
Hello, everybody!
На данный момент один только android lint дает только 185 предупреждений. Немного пробежался - многие весьма обоснованы.
Предалаю начать аккуратно рефактирить код. Могу предложить свою помощь с примитивными проблемами - unused imports, bad style и т.п. И более сложными, если наш добрый малый @vortexwolf будет готов к ревью.
Так же могу помочь с запиливанием CI (Travis умеет в статусе бета для андроида).
@vortexwolf, нет ли возражений?

**Comment by Quireg** [comment]
@MarmaladeSky создавай бранчи и делай пул реквесты если есть желание.
