### ISSUE TITLE
Лаг просмотрщика с перезагрузкой TouchWiz-а

### ISSUE THREAD

**Issue by Tarasus** [vortexwolf/2ch-Browser#87]
При просмотре пикч/вебмок из тредов, когда просто листаешь их, вылазит сообщение об ошибке,  заявляющее, что 2chBrowser остановлен, и перезагружается TouchWiz. После этого закрывается просмотрщик пикч/вебмок, выбрасывает назад в тред, и на телефоне сбрасываются обои рабочего стола на стандартные.

Устройство Samsung Galaxy S4 GT-I9500 
Под Android 5.0.1

**Comment by Quireg** [comment]
Падало на гифке в случае использования libgif.so. Должно быть пофикшено
