### ISSUE TITLE
Don't you die on me, damn it!

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [vortexwolf/2ch-Browser#88]
Vortexwolf, вернись, я все прощу!
В /mobi новый тред - зайди, если все еще жив.

**Comment by vortexwolf** [comment]
Да что там? Вроде изменения АПИ не было, приложение работает еще.

**Comment by nbmrjuhneibkr** [comment]
Там список реквестов , который накапливается и постится снова и снова уже неизвестно сколько времени в надежде, что разработка приложения когда-нибудь возобновится. Я могу каждый реквест сюда отдельно запостить, если это хоть как-то поможет.

**Comment by vortexwolf** [comment]
Из списка часть реквестов сложно выполнимы, и многие не настолько критичны. Какие-то простые можно будет сделать, надо будет посмотреть.

**Comment by nbmrjuhneibkr** [comment]
Приоритетное:
- Отображение восьми прикрепленных файлов (постинг не так важен).
- Защита от случайного удаления закладок.

Менее приоритетное, но тоже актуальное:
- Сохранение webm из галереи с превью
- Свежий список досок и значения бамплимита.
  Надеюсь, это реализовать не слишком сложно.

Баги:
- Баг с размером кэша все еще есть (у меня там 100МБ сейчас), будет очень хорошо, если все-таки получится его найти, а заодно сделать лимит настраиваемым.
- И еще баг, из-за которого невозможно создавать треды в /d/ - вот это довольно важно.

Остальное попадает в категорию "все годы без этого жили, и дальше как-то проживем":
- Поиск текста в треде
- Подсветка нажатий на ссылки ответов
- Кнопка прокрутки к новым постам
- Кнопки разметки текста с латиницей вместо кириллицы (английский язык интерфейса есть же)
- Перезагрузка треда без очистки всего кэша

Но это не значит, что эти изменения не сделали бы приложение лучше.

**Comment by nbmrjuhneibkr** [comment]
Ну так что, будет отображение восьми файлов, или это приложение можно официально считать мертвым?

**Comment by vortexwolf** [comment]
У меня не получилось купить пасскод с моей карточкой, поэтому я не смог ничего сделать.

**Comment by nbmrjuhneibkr** [comment]
Как может быть нужен пасскод для того, чтобы сделать ОТОБРАЖЕНИЕ восьми файлов? Это какой-то бред. Мы же не про постинг говорим. Эти файлы видны всем без каких-либо пасскодов. Всем, кроме пользователей 2ch Browser.

**Comment by vortexwolf** [comment]
Отобразить 8 файлов возможно и сейчас. Но остальную поддержку пасскодов получится сделать только когда можно будет их купить через paypal.

**Comment by nbmrjuhneibkr** [comment]
Плевать на пасскоды, а отображение нужно прямо сейчас, без этого часть контента на сайте недоступна же.

**Comment by nbmrjuhneibkr** [comment]
Так ждать нам обновление, или нет? Я просто хочу наконец-то понять, есть ли какой-то смысл дальше писать здесь, составлять списки багов/реквестов в треде и вообще пользоваться этим приложением.

**Comment by vortexwolf** [comment]
Что-нибудь простое буду иногда исправлять. Но слишком сложные реквесты не сделаю. Список как раз содержит некоторые сложные фичи, которые никак не получится сделать.
Поэтому в обновлении ничего сильно не изменится, может только что-нибудь по мелочи исправлю.

**Comment by nbmrjuhneibkr** [comment]
Спасибо за обновление. Теперь весь контент на сайте снова доступен.
Если в ближайшем будущем планируется еще обновление, то очень хотелось бы увидеть там три вещи:
- Удаление закладок длинным нажатием вместо кнопок в списке, которые очень легко нажать случайно.
- Сохранение webm из галереи при использовании внешнего плеера - сейчас кнопка "сохранить" есть только тогда, когда включен встроенный WebView/VideoView-плеер.
- Возможность создавать треды в /d/. Сейчас их там создать никак нельзя. Если без файла - "прикрепите файл", если с файлом - "тип файла не поддерживается".

Не думаю, что эти вещи требуют внесения фундаментальных изменений в код.

**Comment by vortexwolf** [comment]
Создание тредов в /d я попробовал исправить в этом обновлении, но не проверял. Надо будет проверить.
Первые 2 пункта должно быть не сложно сделать, попробую сделать на этой неделе или в воскресенье.

**Comment by nbmrjuhneibkr** [comment]
Спасибо за обновление. Проблемы с закладками и /d/ решены. Нерешенной остается только проблема с webm.

**Comment by Quireg** [comment]
@nbmrjuhneibkr я добавил сохранение webm, могу тебе собрать apk для тестирования.

**Comment by nbmrjuhneibkr** [comment]
@Quireg для начала пусть кто-нибудь вот это https://github.com/vortexwolf/2ch-Browser/issues/106 пофиксит - а потом уже и протестировать можно будет.

**Comment by Quireg** [comment]
@nbmrjuhneibkr для начала давай не будем говорить кто что кому тут должен. Ты просил фичу, я тебе запилил.

**Comment by nbmrjuhneibkr** [comment]
@Quireg просто фича не такая важная, чтобы только из-за нее тестировать. Насколько я понимаю, тестовая версия поверх оригинальной не встанет, так что повод для тестирования должен оправдывать затраты времени на ручной бэкап закладок из установленного приложения.

**Comment by Quireg** [comment]
@nbmrjuhneibkr тестовые билды должны без проблем ставиться по верх обычных.
