### ISSUE TITLE
Список досок

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [vortexwolf/2ch-Browser#89]
Список нужно обновить. Снова. После обновления пропали /bo/, /izd/ и, возможно, что-то еще.

**Comment by vortexwolf** [comment]
Я их убрал, т.к. их не было на главной странице. Они перенесены в "Прочие доски" на сайте, поэтому я думаю что их можно добавить вручную кому нужно.
Всего 150 досок, по любому какие-то не нужно показывать.

**Comment by nbmrjuhneibkr** [comment]
Кто-то пользуется главной? По-моему, большинство людей даже не помнит о ее существовании. Предлагаю использовать не список с главной, а список, отображающийся в тредах/досках, т.к. он более полный. Кстати, /bo/ - не пользовательская доска, и в "прочих досках" ее нет, а на главную просто кто-то забыл добавить.

Было бы здорово, если бы список досок (в т.ч. и пользовательских) мог загружаться с сервера. Тогда в будущем не пришлось бы ничего менять. Заодно и значения бамплимита можно было бы автоматически обновлять - я точно помню, что они там где-то были.

**Comment by Quireg** [comment]
@nbmrjuhneibkr список досок теперь загружается с сервера с указанием текущего бамплимита.
