### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [vortexwolf/2ch-Browser#90]
Насколько я понимаю, этот зонд остался с тех времен, когда приложение еще жило активной жизнью и было доступно в Маркете. Ящитаю, что надо его убрать по нескольким причинам:
1. В данный момент наверняка ни для чего не используется.
2. Жалобы на зонды от пользователей.
3. Ибо нефиг.

**Comment by vortexwolf** [comment]
Да, я аналитикой уже давно не пользуюсь. Удалил из проекта в последнем коммите.
