### ISSUE TITLE
Сломаны пасскоды

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [vortexwolf/2ch-Browser#94]
Цитата 1:

> В последнем билде клиента вортекса вроде как не работает пасскод, ибо я убрал условие проверки необходимости капчи и сделал всегда принудительно капчу использовать для ответа в любой тред.
> Я уже сказал - дадут пасскод - подправлю.
> Но покупать желания нет.
- https://github.com/wildflypower

Цитата 2:

> Просьба Вортексу ожить и написать на admin@2ch.hk.
> Мы пытаемся его найти около месяца.
> Предоставим новое апи, пасскод любой, который нужен и новое апи для отключения капчи в мобильном приложении (как в The Chan для Windows).
- Модератор /mobi/

**Comment by kolokolovg** [comment]
Будет пасскод я исправлю и верну пулреквестом.

**Comment by vortexwolf** [comment]
Отправлю письмо тогда. А то я так и не осилил купить пасскод из-за неправильной банковской карты.

**Comment by kolokolovg** [comment]
скинь и мне то что тебе абу скинул по поводу апи.

**Comment by vortexwolf** [comment]
Напиши свой e-mail, я отправлю письмом

**Comment by kolokolovg** [comment]
wfpower yandex ru

**Comment by kolokolovg** [comment]
В пулреквесте версия с апкапчей.

**Comment by vortexwolf** [comment]
Должны быть исправлены в последней версии с апп капчей.
