### ISSUE TITLE
Проблема с HTTPS

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [vortexwolf/2ch-Browser#95]
В треде в /mobi/ есть минимум два человека, у которых не работает HTTPS в 2ch Browser - выдает ошибку "сертификат не может быть проверен". При этом отключение проверки сертификата тоже не помогает, а помогает только полное отключение HTTPS. С связи с тем, что у других такой проблемы нет, это можно было бы списать на провайдера, но дело в том, что у тех, кто словил эту проблему, в любых других мобильных клиентах HTTPS работает нормально.

**Comment by vortexwolf** [comment]
Здесь как всегда - я не могу воспроизвести на своем телефоне, поэтому не представляю что исправлять. Если баг появится и у меня - тогда и смогу разобраться.

**Comment by nbmrjuhneibkr** [comment]
Можно же сделать тестовый билд, который будет писать логи, а потом на основе этих логов попытаться найти причину проблемы... А впрочем, может действительно не стоит оно того, если почти у всех и так работает.

**Comment by Philolaus** [comment]
На этом клиенте. Ни в Wi-Fi (причём с компа удаётся зайти, соединение защищённое, сертификат правильный), ни в мобильных сетях. В Overchan и Dashchan всё и везде работает. Может, есть какой-нибудь вариант с тестовым клиентом и логами?
26-я версия.

**Comment by vortexwolf** [comment]
Вероятно, это не в https проблема, а в cloudflare-капче. На других клиентах эта капча когда-то давно была заполнена и теперь пропускает. В этом приложении ничего не показывает, т.к. я не знаю как именно эту капчу проверить.
Как вариант, ты можешь удалить все куки двача в обычном браузере и перезагрузить страницу. Если будет требовать капчу на доступ к сайту - нужен исходных код этой страницы.

**Comment by kolokolovg** [comment]
Работая над реализацией хттп2 заметил одну вещь

Нынешний сертификат сайта позволяет корректно работать только с .hk доменом.
Если использовать какой то друго типа so pm то ничего не работает.

У кого ошибки с ссл - пропишите использовать только hk Домен

**Comment by nbmrjuhneibkr** [comment]
Если проблема на самом деле в Cloudflare, и с HTTPS никак не связана, то было бы очень полезно, если бы приложение могло корректно об этом сообщать.

**Comment by Philolaus** [comment]
После очистки куки в браузере на компе почему-то заработало в смартфоне. Совпадение, наверное.
