### ISSUE TITLE
Не работает https

### ISSUE THREAD

**Issue by Philolaus** [vortexwolf/2ch-Browser#99]
На этом клиенте. Ни в Wi-Fi (причём с компа удаётся зайти, соединение защищённое, сертификат правильный), ни в мобильных сетях. В Overchan и Dashchan всё и везде работает. Может, есть какой-нибудь вариант с тестовым клиентом и логами?

**Comment by kolokolovg** [comment]
https://github.com/vortexwolf/2ch-Browser/issues/95
